In [1]:
import torch

In [2]:
a = [1.0, 2.0, 3.0]

In [3]:
a[2]

3.0

In [4]:
a

[1.0, 2.0, 3.0]

## Why python lists not suitable?

In [5]:
import torch
a = torch.ones(3)

In [6]:
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2]=2423.0


In [10]:
a

tensor([1.0000e+00, 1.0000e+00, 2.4230e+03])

In [11]:
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [12]:
points

tensor([1., 4., 2., 1., 3., 5.])

In [13]:
points = torch.tensor([1.0,4.0, 2.0, 1.0, 3.0, 5.0])

In [14]:
points

tensor([1., 4., 2., 1., 3., 5.])

In [19]:
float(points[0]), float(points[1])

(1.0, 4.0)

In [21]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])

In [22]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [23]:
points.shape

torch.Size([3, 2])

In [24]:
points = torch.zeros(3,2)

In [25]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])

In [27]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [28]:
points[0,1]

tensor(4.)

In [29]:
points[0]

tensor([1., 4.])

In [30]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [31]:
points_storage = points.storage()

In [35]:
points_storage[0]

1.0

In [33]:
points.storage()[1]

4.0

In [36]:
points.storage()[0] = 2.0


In [37]:
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [38]:
second_point = points[1]
second_point.storage_offset()

2

In [39]:
second_point.size()

torch.Size([2])

In [40]:
second_point.shape

torch.Size([2])

In [41]:
points.stride()

(2, 1)

In [42]:
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [44]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [45]:
second_point.storage_offset()

2

In [46]:
second_point.stride()

(1,)

In [47]:
# changing subtensor has a side effect on tensor as well
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0

In [48]:
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [49]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0


In [50]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [51]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [53]:
id(points.storage()) == id(points_t.storage())

True

In [54]:
id?

In [56]:
print(points.stride())

(2, 1)


In [57]:
print(points_t.stride())

(1, 2)


In [58]:
some_tensor = torch.ones(3,4,5)
some_tensor_t = some_tensor.transpose(0,2)
some_tensor.shape

torch.Size([3, 4, 5])

In [59]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [60]:
some_tensor.stride()

(20, 5, 1)

In [61]:
some_tensor_t.stride()

(1, 5, 20)

In [63]:
print(points.is_contiguous())
points_t.is_contiguous()

True


False

In [64]:
# continuos array for transpose as well
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [66]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [67]:
points_t.stride()

(1, 2)

In [69]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [70]:
points_t_cont.stride()


(3, 1)

In [71]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [73]:
# Numeric types
double_point = torch.ones(10,2, dtype=torch.double)
short_point = torch.tensor([[1, 2], [3,4]], dtype=torch.short)

In [74]:
short_point.dtype

torch.int16

In [75]:
double_point = torch.zeros(10,2).double()
short_point = torch.zeros(10,2).short()

In [76]:
double_point = torch.zeros(10,2).to(torch.double)
short_point = torch.zeros(10,2).to(torch.short)

In [77]:
points = torch.randn(10,2)

In [78]:
points

tensor([[-3.2277e-01, -9.2111e-01],
        [-8.8877e-02,  1.0916e+00],
        [-1.1543e+00,  3.3813e-01],
        [-1.6163e+00,  1.7540e-01],
        [ 1.7829e+00, -1.8725e+00],
        [ 3.8552e-01, -5.8418e-01],
        [-1.4454e+00, -5.3725e-01],
        [-1.4850e+00, -3.6230e-01],
        [-1.4593e+00, -4.9239e-01],
        [ 5.1560e-02,  4.2656e-04]])

In [79]:
short_point = points.type(torch.short)

In [80]:
points.type?

In [81]:
short_point


tensor([[ 0,  0],
        [ 0,  1],
        [-1,  0],
        [-1,  0],
        [ 1, -1],
        [ 0,  0],
        [-1,  0],
        [-1,  0],
        [-1,  0],
        [ 0,  0]], dtype=torch.int16)

In [82]:
points[1:]

tensor([[-8.8877e-02,  1.0916e+00],
        [-1.1543e+00,  3.3813e-01],
        [-1.6163e+00,  1.7540e-01],
        [ 1.7829e+00, -1.8725e+00],
        [ 3.8552e-01, -5.8418e-01],
        [-1.4454e+00, -5.3725e-01],
        [-1.4850e+00, -3.6230e-01],
        [-1.4593e+00, -4.9239e-01],
        [ 5.1560e-02,  4.2656e-04]])

In [83]:
points[1:, :]

tensor([[-8.8877e-02,  1.0916e+00],
        [-1.1543e+00,  3.3813e-01],
        [-1.6163e+00,  1.7540e-01],
        [ 1.7829e+00, -1.8725e+00],
        [ 3.8552e-01, -5.8418e-01],
        [-1.4454e+00, -5.3725e-01],
        [-1.4850e+00, -3.6230e-01],
        [-1.4593e+00, -4.9239e-01],
        [ 5.1560e-02,  4.2656e-04]])

In [84]:
points[1:, 0]

tensor([-0.0889, -1.1543, -1.6163,  1.7829,  0.3855, -1.4454, -1.4850, -1.4593,
         0.0516])

In [85]:
points

tensor([[-3.2277e-01, -9.2111e-01],
        [-8.8877e-02,  1.0916e+00],
        [-1.1543e+00,  3.3813e-01],
        [-1.6163e+00,  1.7540e-01],
        [ 1.7829e+00, -1.8725e+00],
        [ 3.8552e-01, -5.8418e-01],
        [-1.4454e+00, -5.3725e-01],
        [-1.4850e+00, -3.6230e-01],
        [-1.4593e+00, -4.9239e-01],
        [ 5.1560e-02,  4.2656e-04]])

In [86]:
points = torch.ones(3, 4)
points_np = points.numpy()

In [87]:
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [88]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
torch.save(points, 'kb.t')

In [90]:
kb = torch.load('kb.t')

In [91]:
kb

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
import h5py

In [93]:
points_gpu = torch.tensor([1.0,4.0, 2.0, 1.0, 3.0, 5.0], device='cuda')

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [94]:
a = torch.ones(3,2)

In [95]:
a_t = torch.transpose(a, 0, 1)

In [96]:
a_t = a.transpose(0,1)

In [97]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [98]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [99]:
a = list(range(9))

In [100]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [101]:
t1 = torch.tensor(a)

In [102]:
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
t1.size()

torch.Size([9])

In [105]:
t1.stride()

(1,)

In [107]:
b = t1.view(3,3)

In [108]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [109]:
b[1:,1:]

tensor([[4, 5],
        [7, 8]])