In [1]:
import numpy as np
import torch

In [5]:
import imageio

imag_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')
imag_arr.shape

(720, 1280, 3)

In [4]:
! python3 -m pip install imageio

     |████████████████████████████████| 3.3MB 148kB/s eta 0:00:01
You should consider upgrading via the 'pip install --upgrade pip' command.


In [6]:
img = torch.from_numpy(imag_arr)


In [8]:
img

tensor([[[ 77,  45,  22],
         [ 77,  45,  22],
         [ 78,  46,  21],
         ...,
         [118,  78,  52],
         [117,  77,  51],
         [116,  76,  51]],

        [[ 75,  43,  20],
         [ 76,  44,  21],
         [ 77,  45,  20],
         ...,
         [118,  78,  52],
         [117,  77,  51],
         [116,  76,  50]],

        [[ 74,  39,  17],
         [ 75,  41,  16],
         [ 77,  43,  18],
         ...,
         [119,  80,  51],
         [117,  77,  51],
         [116,  76,  50]],

        ...,

        [[215, 165,  78],
         [216, 166,  79],
         [217, 167,  80],
         ...,
         [172, 122,  51],
         [174, 124,  53],
         [174, 124,  53]],

        [[215, 165,  78],
         [216, 166,  79],
         [217, 167,  80],
         ...,
         [173, 123,  54],
         [174, 124,  55],
         [174, 124,  55]],

        [[215, 165,  78],
         [216, 166,  79],
         [217, 167,  80],
         ...,
         [159, 108,  42],
        

In [12]:
img.shape

torch.Size([720, 1280, 3])

In [10]:
out = torch.transpose(img,0,2)

In [11]:
out

tensor([[[ 77,  75,  74,  ..., 215, 215, 215],
         [ 77,  76,  75,  ..., 216, 216, 216],
         [ 78,  77,  77,  ..., 217, 217, 217],
         ...,
         [118, 118, 119,  ..., 172, 173, 159],
         [117, 117, 117,  ..., 174, 174, 158],
         [116, 116, 116,  ..., 174, 174, 158]],

        [[ 45,  43,  39,  ..., 165, 165, 165],
         [ 45,  44,  41,  ..., 166, 166, 166],
         [ 46,  45,  43,  ..., 167, 167, 167],
         ...,
         [ 78,  78,  80,  ..., 122, 123, 108],
         [ 77,  77,  77,  ..., 124, 124, 107],
         [ 76,  76,  76,  ..., 124, 124, 107]],

        [[ 22,  20,  17,  ...,  78,  78,  78],
         [ 22,  21,  16,  ...,  79,  79,  79],
         [ 21,  20,  18,  ...,  80,  80,  80],
         ...,
         [ 52,  52,  51,  ...,  51,  54,  42],
         [ 51,  51,  51,  ...,  53,  55,  41],
         [ 51,  50,  50,  ...,  53,  55,  41]]], dtype=torch.uint8)

In [13]:
out.shape

torch.Size([3, 1280, 720])

In [15]:
batch_size = 100
batch = torch.zeros(100,3,256,256, dtype=torch.uint8)

In [16]:
import os
data_dir = '../data/p1ch4/image-dog'

In [17]:
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png']

In [18]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(filename)
    batch[i] = torch.transpose(torch.from_numpy(img_arr), 0,2)

In [19]:
batch 

tensor([[[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]],


        [[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0

In [22]:
batch = batch.float()
batch /= 255.0

In [24]:
batch.shape

torch.Size([100, 3, 256, 256])

In [26]:
n_channels = batch.shape[1]
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std
